# Generated by Django 5.1 on 2024-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0002_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(default=1, to='oddam_w_dobre_rece.category'),
        ),
    ]
