# Generated by Django 5.1 on 2024-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0004_alter_institution_categories_alter_institution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
