# Generated by Django 5.1 on 2024-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0005_donation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
