# Generated by Django 5.1 on 2024-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0006_donation_city_donation_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
